spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  config:
    import: "optional:file:../.env[.properties]"

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000